image: node:10.15.0 # change to match your node version

cache:
  paths:
    - node_modules/

variables:
    PUBLIC_URL: "/sw"

before_script:
  - npm install

pages:
  stage: deploy
  script:
    - CI=true npm run build
    - rm -rf public
    - mv build public # move everything in build to public directory
    - cp public/index.html public/404.html # https://stackoverflow.com/questions/46684607/gitlab-pages-and-react-router
  artifacts:
    paths:
      - public # GitLab pages serve from a 'public' directory
  only:
    - master # run on master branch
